<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="event">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="comment" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="eid" type="xs:ID" use="required"/>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="OCCURRENCE"/>
						<xs:enumeration value="PERCEPTION"/>
						<xs:enumeration value="REPORTING"/>
						<xs:enumeration value="ASPECTUAL"/>
						<xs:enumeration value="STATE"/>
						<xs:enumeration value="I_STATE"/>
						<xs:enumeration value="I_ACTION"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>
