<!ELEMENT TimeML (DOCID?, DCT, TEXT)>

<!ELEMENT DOCID (#PCDATA)>

<!ELEMENT DCT (TIMEX3)>
<!ELEMENT TEXT (#PCDATA | EVENT | TIMEX3)*>

<!-- EVENT -->
<!ELEMENT EVENT (#PCDATA)>
<!ATTLIST EVENT
  eid ID #REQUIRED
  class (OCCURRENCE | STATE | REPORTING | ASPECTUAL | I_ACTION | I_STATE | PERCEPTION) #REQUIRED
>

<!-- MAKEINSTANCE -->
<!ELEMENT MAKEINSTANCE EMPTY>
<!ATTLIST MAKEINSTANCE
  eiid ID #REQUIRED
  eventID IDREF #REQUIRED
  tense (PAST | PRESENT | FUTURE | NONE) #IMPLIED
  aspect (NONE | PERFECTIVE | PROGRESSIVE | PERFECTIVE_PROGRESSIVE) #IMPLIED
  polarity (POS | NEG) "POS"
  modality CDATA #IMPLIED
>

<!-- TIMEX3 -->
<!ELEMENT TIMEX3 (#PCDATA)>
<!ATTLIST TIMEX3
  tid ID #REQUIRED
  type (DATE | TIME | DURATION | SET) #REQUIRED
  value CDATA #IMPLIED
  mod (BEFORE | AFTER | APPROX | START | END) #IMPLIED
  anchorTimeID IDREF #IMPLIED
  functionInDocument (CREATION_TIME | PUBLICATION_TIME | NONE) #IMPLIED
  temporalFunction (true | false) "false"
>

<!-- TLINK -->
<!ELEMENT TLINK EMPTY>
<!ATTLIST TLINK
  lid ID #REQUIRED
  eventInstanceID IDREF #IMPLIED
  relatedToEventInstance IDREF #IMPLIED
  relatedToTime IDREF #IMPLIED
  relType (BEFORE | AFTER | INCLUDES | IS_INCLUDED | SIMULTANEOUS | BEGINS | ENDS | VAGUE) #REQUIRED
>
